# Use official n8n image
FROM n8nio/n8n:latest

# Set timezone (important for your workflows)
ENV GENERIC_TIMEZONE=Asia/Kolkata

# Expose n8n port
EXPOSE 5678

# Run n8n (default entrypoint)
CMD ["n8n"]
